### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by scharada** [johnknoop/MongoRepository#12]
hi. can you please provide samples on how to use the various calls and features ? 
i am mainly talking about the advanced ones. this for example, how to update and return the full document when found ? 
'var entityAfterUpdate = await repository.FindOneAndUpdateAsync(
	filter: x => x.SomeProperty.StartsWith("Hello"),
	update: x => x.PullFilter(y => y.SomeCollection, y => y.SomeOtherProperty == 5),
	returnProjection: x => new {
		x.SomeCollection
	},
	returnedDocumentState: ReturnedDocumentState.AfterUpdate,
	upsert: true
);'

**Comment by johnknoop** [comment]
Hi

```cshart
var updatedEntity = await repo.FindOneAndUpdateAsync(
    filter: x => x.SomeProperty.StartsWith("Hello"),
    update: x => x.PullFilter(y => y.SomeCollection, y => y.SomeOtherProperty == 5),
    returnProjection: x => x,
    upsert: true
);
```
should update and return the whole document.
