### ISSUE TITLE
SoftDelete question.

### ISSUE THREAD

**Issue by scharada** [johnknoop/MongoRepository#13]
generally , we set a flag "IsDeleted to use with softDelete. when querying records we use includeDeleted flag to return records we need even if they are set as deleted.
the repo seems to move the record to a separate collection.  how to di tell the repo to include those in my queries ? i don't want to restore them, just include them in the results ...

**Comment by johnknoop** [comment]
Hi

It sounds like you have two options:

A) Don't use the soft-restore feature of this library at all, but stick with your IsDeleted flag.

B) Perform two queries: your normal one, and also `repo.ListTrashAsync()` and then merge the results.
