### ISSUE TITLE
What should I do in the Asp.Net Core 2.1 project to use it better?

### ISSUE THREAD

**Issue by oTcom** [johnknoop/MongoRepository#2]
Can you provide an example of using Asp.Net Core 2.1

**Comment by johnknoop** [comment]
Hi @oTcom 

The example from the read.me works in .NET Core 2.1. As long as you have an instance of `IMongoClient`, you can call the `GetRepository<TEntity>` extension method. Just make sure you've configured the mappings first (see the first example on the readme, and dont forget `.Build()` at the end.

**Comment by oTcom** [comment]
Hi @johnknoop 
Nice explanation, thank you very much.
