### ISSUE TITLE
How to Query $geoNear? 

### ISSUE THREAD

**Issue by todosrc** [johnknoop/MongoRepository#24]
How to Query $geoNear?  how to get collection instance?

==================================

Here's an example of how to use $geoNear in C#:

var collection = database.GetCollection<BsonDocument>("places");
var geoNearOptions = new BsonDocument
{
    { "near", new BsonDocument { { "type", "Point" }, { "coordinates", new BsonArray { -73.97, 40.77 } } } },
    { "distanceField", "distance" },
    { "spherical", true },
    { "maxDistance", 5000 }
};
var pipeline = new BsonDocument[]
{
    new BsonDocument
    {
        { "$geoNear", geoNearOptions }
    }
};
var results = await collection.AggregateAsync<BsonDocument>(pipeline);

**Comment by johnknoop** [comment]
Hi @todosrc 

I haven't used geoNear myself, but this (untested) code should work for geoWithin:

```cs
await repository.Aggregate()
  .Match(Builders<Person>.Filter.GeoWithin(x => x.Home, GeoJson.Polygon(new GeoJson2DCoordinates[]
  {
    GeoJson.Position(-74.0011869, 40.752482),
    // ... more coordinates
  })))
  .ToListAsync();
```

**Comment by todosrc** [comment]
thakyou , any idea?  if provide method for get collection instance  like ..  repository.GetCollection();   ,that usefull for native pipeline query

**Comment by todosrc** [comment]
> Hi @todosrc
> 
> I haven't used geoNear myself, but this (untested) code should work for geoWithin:
> 
> ```cs
> await repository.Aggregate()
>   .Match(Builders<Person>.Filter.GeoWithin(x => x.Home, GeoJson.Polygon(new GeoJson2DCoordinates[]
>   {
>     GeoJson.Position(-74.0011869, 40.752482),
>     // ... more coordinates
>   })))
>   .ToListAsync();
> ```

i will test

**Comment by johnknoop** [comment]
> thakyou , any idea? if provide method for get collection instance like .. repository.GetCollection(); ,that usefull for native pipeline query

Most of the native API:s for querying are already exposed, though various methods:

`repository.Aggregate()` will return a native `IAggregateFluent<TEntity>`, just like a MongoCollection would. `repository.Find(expression)` and `repository.GetAll()` will return a native `IFindFluent<TEntity>`. And if you prefer LINQ, `repository.Query()` will return an `IMongoQueryable`.

Is there another one you're looking for, that would be accessible through an `IMongoCollection`?

**Comment by todosrc** [comment]
The Native MongoDB.NET driver provides a lot of powerful features for interacting with MongoDB databases, including support for complex filtering and aggregation operations. However, there are some scenarios where the builder syntax provided by the driver's Builders<Model>.Filter class may not be sufficient for the task at hand.

In those cases, developers can use the IMongoCollection interface, which is part of the driver's core API, to interact with MongoDB directly. This interface provides a more low-level way to interact with MongoDB databases and allows developers to perform advanced queries and other operations that may not be possible with the builder syntax alone.

there are certainly cases where using IMongoCollection directly may be necessary to achieve certain functionality.

**Comment by todosrc** [comment]
> > Hi @todosrc
> > I haven't used geoNear myself, but this (untested) code should work for geoWithin:
> > ```cs
> > await repository.Aggregate()
> >   .Match(Builders<Person>.Filter.GeoWithin(x => x.Home, GeoJson.Polygon(new GeoJson2DCoordinates[]
> >   {
> >     GeoJson.Position(-74.0011869, 40.752482),
> >     // ... more coordinates
> >   })))
> >   .ToListAsync();
> > ```
> 
> i will test

**Comment by johnknoop** [comment]
@todosrc I don't mind exposing the wrapped MongoCollection. I'm just curious about which parts of its API you want access to, in case there's something I could make accessible in a more direct way.
