### ISSUE TITLE
Cannot work with a database name that includes numeric characters.

### ISSUE THREAD

**Issue by todosrc** [johnknoop/MongoRepository#25]
Not working :
 
 tenantKey = "main"
 MongoRepository.Configure()
            .DatabasePerTenant("store1", db => db
                .Map<Product>("products")
                
 var items = await _productRepo.GetAll().ToListAsync();  
 result =>  empty rows
 
 because this library automatically cleans up and removes the number '1' from the loaded database name configuration on the repository instance., 
 
   what the reason ?  for remove number from DatabaseName
   
 ________________________________________________________________________________
 working version :
 
  *Mongodb Allowed number *

 var database = mongoClient.GetDatabase("main_store1");
                        var collection = database.GetCollection<Product>("products");
                        var documents = collection.Find(Builders<Product>.Filter.Empty).ToList();  
 ________________________________________________________________________________

**Comment by johnknoop** [comment]
Hi @todosrc 

Since database names will also contain the names of the tenants, which typically aren't controlled by your application, the database name is "washed" from any characters except a-z and _. This is to get rid of special characters that MongoDB will not allow as database names. Perhaps numeric characters could have been allowed, I've never thought about that TBH.

I would need to do some testing to make sure database names with numbers in them are valid in different versions of MongoDB. In the meantime, would it be a workaround for you to name it "storeOne" instead of "store1" until I have a fix for this?

**Comment by todosrc** [comment]
@johnknoop  
Thank you for your reply. I workaround the issue by using storeOne. By the way, my project is using [MongoDB Atlas] on a free sharing package, and that service has no issues with setting a database name with a number.

Refer: https://www.mongodb.com/docs/manual/reference/limits/#naming-restrictions

**Comment by todosrc** [comment]
the root issue is WashDatabaseName() function in MongoConfiguration.cs

need update from 
  
```

  private static string WashDatabaseName(string name)
      {
	      return new string(name.Where(letter => letter >= 97 && letter <= 122 || letter >= 65 && letter <= 90).ToArray());
      }
```
to 

```
    private static string WashDatabaseName(string name)
    {
        return new string(name.Where(letter => 
            (letter >= 97 && letter <= 122) || // lowercase letters
            (letter >= 65 && letter <= 90) || // uppercase letters
            (letter >= 48 && letter <= 57)    // numeric digits
        ).ToArray());
    }
```

**Comment by sven5** [comment]
The hyphen "-" seems also to be washed out of the database name. 😢

**Comment by johnknoop** [comment]
@sven5 I will address this and make sure both hyphens and digits are allowed.

**Comment by johnknoop** [comment]
@sven5 @todosrc there's now a [preview version out](https://www.nuget.org/packages/JohnKnoop.MongoRepository/7.0.0-preview2) that supports all characters except [those restricted by MongoDB](https://www.mongodb.com/docs/manual/reference/limits/#mongodb-limit-Restrictions-on-Database-Names-for-Windows).
