### ISSUE TITLE
Can updating and deleting methods add return values?

### ISSUE THREAD

**Issue by oTcom** [johnknoop/MongoRepository#4]
Add return DeleteResult，UpdateResult，ReplaceOneResult...
Thanks

**Comment by johnknoop** [comment]
Hi @oTcom 

It's something I've been meaning to do for a while. `ReplaceOneAsync` already does it, but not the rest as you've noticied.

It's on the shortlist of things to do.

**Comment by johnknoop** [comment]
@oTcom  I just published a pre-release of version 3.0.0 to Nuget with the changes you requested.

**Comment by scharada** [comment]
all inserts and updates should have calls that return the inserted or updated entity or an operation result. my suggestion is to make each call return a tuple  <operationcount, entity> where operation is insert or update or delete ...
the user then does what he wants with it.

**Comment by johnknoop** [comment]
@scharada  That's unfortunately not something that the MongoDB driver exposes. All you get back from InsertOne is a `Task`.
