### ISSUE TITLE
Add conditional updates to arrays in IRepository

### ISSUE THREAD

**Issue by oTcom** [johnknoop/MongoRepository#7]
Hi.
  Increase the array update operator.
  -     db.coll.update({}, {$set: {“a.$[i].b”: 2}}, {**arrayFilters**: [{“i.b”: 0}]})
  Link to https://jira.mongodb.org/browse/SERVER-1243

**Comment by oTcom** [comment]
Add arrayfilters parameters。

MongoCollection.UpdateOneAsync(filter, update, new UpdateOptions { IsUpsert = upsert ,ArrayFilters=arrayfilters }).ConfigureAwait(false);

**Comment by johnknoop** [comment]
Can you give an example of what you want to do? It might be possible already.

**Comment by oTcom** [comment]
I want to UpdateOneAsync the method to add ArrayFilters.
`Task<UpdateResult> UpdateOneAsync(string filter, string update,IEnumerable<ArrayFilterDefinition> arrayFilters,bool upsert = false);`

Link to https://stackoverflow.com/questions/51621667/how-to-update-item-from-array-nested-within-array/51622030#51622030

**Comment by oTcom** [comment]
I think every Update method, you can customize the updateoptions.
```
 public async Task<UpdateResult> UpdateOneAsync<TDerived>(Expression<Func<TDerived, bool>> filter, Func<UpdateDefinitionBuilder<TDerived>, UpdateDefinition<TDerived>> update, UpdateOptions options = null) where TDerived : TEntity
        {
            await MongoConfiguration.EnsureIndexesAndCap(MongoCollection);
            return await this.MongoCollection.OfType<TDerived>().UpdateOneAsync(filter, update(Builders<TDerived>.Update), options ?? new UpdateOptions { IsUpsert = false }).ConfigureAwait(false);
        }
```

**Comment by johnknoop** [comment]
I will have to think about how to add that in a nice way.

Do you have two levels of nesting, like in the SO question? If you only have one array, this will work:

```csharp
await repo.UpdateOneAsync(
    filter: x => x.Id x.Options.Any(opt => opt.Id == optionId),
    update: x => x.Set(y => y.Options[-1].Name, "New name")
)
```

**Comment by oTcom** [comment]
Yes, multiple levels of nesting, I want to update the specified element in the array, arrayfilters is a good choice；

**Comment by johnknoop** [comment]
@oTcom I just pushed a pre-release version (3.0.0-rc.2) of the package to Nuget, containing new overloads of UpdateOneAsync that accepts an argument of type UpdateOptions.

Feel free to try it out.

**Comment by oTcom** [comment]
Multi - level update operation can't use LINQ, only bsondocument way.

I think should add an overload method for complex situations.


`Task<UpdateResult> UpdateOneAsync(FilterDefinition<TDocument> filter, UpdateDefinition<TDocument> update, UpdateOptions options = null)`

**Comment by johnknoop** [comment]
@oTcom there's now a version 3.0.0-rc.3 on Nuget that accepts `FilterDefinition` instead of only `Expression`.
